apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myapp.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "myapp.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "myapp.name" . }}
    spec:
      containers:
        - name: {{ include "myapp.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: fbriq-bot-secret
                  key: BOT_TOKEN
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: fbriq-bot-secret
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: fbriq-bot-secret
                  key: CLOUDINARY_API_SECRET
            - name: CLOUDINARY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: fbriq-bot-secret
                  key: CLOUDINARY_API_KEY
            - name: NOTIFY_CHAT_ID
              valueFrom:
                secretKeyRef:
                  name: fbriq-bot-secret
                  key: NOTIFY_CHAT_ID
            - name: APPS_SCRIPT_URL
              valueFrom:
                secretKeyRef:
                  name: fbriq-bot-secret
                  key: APPS_SCRIPT_URL
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: fbriq-bot-secret
                  key: MONGODB_URI
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
      imagePullSecrets:
        - name: dockerhub
